version: '3.8'

services:
  weather-api:
    build: .
    ports:
      - "5000:5000"
    container_name: weather-api-backend
    environment:
      - PYTHONUNBUFFERED=1
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    restart: unless-stopped
